jaffle_shop:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: zna84829

      # User/password auth
      user: sung_c
      password: "{{ env_var('SFPASS') }}"

      database: SUNG_DEMO
      warehouse: TRANSFORMING
      schema: dbt_sung
      threads: 16
      client_session_keep_alive: True
      query_tag: